import mongoose, { Schema } from "mongoose";
import crypto from "crypto";

const userSchema = new Schema({
  // TODO add email and password
  // TODO add accessToken with default value of random value generated by crypto
});

export const User = mongoose.model("User", userSchema);
